// ticket-management-app/react-version/src/pages/tickets/TicketManagement.jsx
import React, { useState, useEffect } from 'react'
import { useToast } from '../../contexts/ToastContext'
import TicketForm from './TicketForm'
import TicketCard from './TicketCard'
import Button from '../../components/UI/Button'
import CircleDecoration from '../../components/Decorative/CircleDecoration'

// Mock data storage - in real app, this would be an API
const getStoredTickets = () => {
  const stored = localStorage.getItem('ticketapp_tickets')
  return stored ? JSON.parse(stored) : [
    {
      id: 1,
      title: 'Login issue on mobile app',
      description: 'Users are unable to login through the mobile application. Error message shows "Invalid credentials" even with correct details.',
      status: 'open',
      priority: 'high',
      createdAt: '2024-01-15T10:30:00Z',
      updatedAt: '2024-01-15T10:30:00Z'
    },
    {
      id: 2,
      title: 'Payment gateway integration',
      description: 'Integrate new payment gateway for international transactions.',
      status: 'in_progress',
      priority: 'high',
      createdAt: '2024-01-14T14:20:00Z',
      updatedAt: '2024-01-15T09:15:00Z'
    },
    {
      id: 3,
      title: 'Update user dashboard UI',
      description: 'Redesign the user dashboard to improve usability and add new metrics.',
      status: 'open',
      priority: 'medium',
      createdAt: '2024-01-13T11:45:00Z',
      updatedAt: '2024-01-13T11:45:00Z'
    },
    {
      id: 4,
      title: 'Fix email notification bug',
      description: 'Users are not receiving email notifications for completed actions.',
      status: 'closed',
      priority: 'low',
      createdAt: '2024-01-12T16:10:00Z',
      updatedAt: '2024-01-14T08:30:00Z'
    }
  ]
}

const saveTickets = (tickets) => {
  localStorage.setItem('ticketapp_tickets', JSON.stringify(tickets))
}

function TicketManagement() {
  const [tickets, setTickets] = useState([])
  const [showForm, setShowForm] = useState(false)
  const [editingTicket, setEditingTicket] = useState(null)
  const [filter, setFilter] = useState('all')
  const { addToast } = useToast()

  useEffect(() => {
    setTickets(getStoredTickets())
  }, [])

  const createTicket = (ticketData) => {
    const newTicket = {
      id: Date.now(),
      ...ticketData,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
    
    const updatedTickets = [newTicket, ...tickets]
    setTickets(updatedTickets)
    saveTickets(updatedTickets)
    addToast('Ticket created successfully!', 'success')
    setShowForm(false)
  }

  const updateTicket = (ticketData) => {
    const updatedTickets = tickets.map(ticket =>
      ticket.id === editingTicket.id
        ? { ...ticketData, updatedAt: new Date().toISOString() }
        : ticket
    )
    
    setTickets(updatedTickets)
    saveTickets(updatedTickets)
    addToast('Ticket updated successfully!', 'success')
    setEditingTicket(null)
    setShowForm(false)
  }

  const deleteTicket = (ticketId) => {
    if (window.confirm('Are you sure you want to delete this ticket?')) {
      const updatedTickets = tickets.filter(ticket => ticket.id !== ticketId)
      setTickets(updatedTickets)
      saveTickets(updatedTickets)
      addToast('Ticket deleted successfully!', 'success')
    }
  }

  const handleEdit = (ticket) => {
    setEditingTicket(ticket)
    setShowForm(true)
  }

  const handleCancel = () => {
    setShowForm(false)
    setEditingTicket(null)
  }

  const filteredTickets = tickets.filter(ticket => {
    if (filter === 'all') return true
    return ticket.status === filter
  })

  const statusCounts = {
    all: tickets.length,
    open: tickets.filter(t => t.status === 'open').length,
    in_progress: tickets.filter(t => t.status === 'in_progress').length,
    closed: tickets.filter(t => t.status === 'closed').length
  }

  const FilterButton = ({ status, label }) => (
    <button
      onClick={() => setFilter(status)}
      className={`px-4 py-2 text-sm font-medium rounded-lg transition-colors ${
        filter === status
          ? 'bg-blue-600 text-white'
          : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
      }`}
    >
      {label} ({statusCounts[status]})
    </button>
  )

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Ticket Management</h1>
          <p className="text-gray-600 mt-2">
            Create, view, and manage support tickets
          </p>
        </div>
        
        <Button
          onClick={() => setShowForm(true)}
          className="mt-4 sm:mt-0"
        >
          Create New Ticket
        </Button>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-xl shadow-lg border border-gray-200 p-6 mb-8">
        <div className="flex flex-wrap gap-2">
          <FilterButton status="all" label="All Tickets" />
          <FilterButton status="open" label="Open" />
          <FilterButton status="in_progress" label="In Progress" />
          <FilterButton status="closed" label="Closed" />
        </div>
      </div>

      {/* Content */}
      {showForm ? (
        <TicketForm
          ticket={editingTicket}
          onSubmit={editingTicket ? updateTicket : createTicket}
          onCancel={handleCancel}
        />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredTickets.map(ticket => (
            <TicketCard
              key={ticket.id}
              ticket={ticket}
              onEdit={handleEdit}
              onDelete={deleteTicket}
            />
          ))}
          
          {filteredTickets.length === 0 && (
            <div className="col-span-full text-center py-12">
              <div className="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg className="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">No tickets found</h3>
              <p className="text-gray-600 mb-4">
                {filter === 'all' 
                  ? "You haven't created any tickets yet."
                  : `No ${filter.replace('_', ' ')} tickets found.`
                }
              </p>
              <Button onClick={() => setShowForm(true)}>
                Create Your First Ticket
              </Button>
            </div>
          )}
        </div>
      )}

      {/* Decorative Elements */}
      <CircleDecoration 
        size="medium" 
        color="blue" 
        className="absolute bottom-10 right-10 opacity-20" 
      />
      <CircleDecoration 
        size="small" 
        color="green" 
        className="absolute top-20 left-10 opacity-20" 
      />
    </div>
  )
}

export default TicketManagement

// ticket-management-app/vue-version/src/pages/tickets/TicketManagement.vue
<template>
  <Layout>
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <!-- Header -->
      <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-8">
        <div>
          <h1 class="text-3xl font-bold text-gray-900">Ticket Management</h1>
          <p class="text-gray-600 mt-2">
            Create, view, and manage support tickets
          </p>
        </div>
        
        <Button
          @click="showForm = true"
          class="mt-4 sm:mt-0"
        >
          Create New Ticket
        </Button>
      </div>

      <!-- Filters -->
      <div class="bg-white rounded-xl shadow-lg border border-gray-200 p-6 mb-8">
        <div class="flex flex-wrap gap-2">
          <button
            v-for="filterOption in filterOptions"
            :key="filterOption.status"
            @click="filter = filterOption.status"
            :class="[
              'px-4 py-2 text-sm font-medium rounded-lg transition-colors',
              filter === filterOption.status
                ? 'bg-blue-600 text-white'
                : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
            ]"
          >
            {{ filterOption.label }} ({{ filterOption.count }})
          </button>
        </div>
      </div>

      <!-- Content -->
      <TicketForm
        v-if="showForm"
        :ticket="editingTicket"
        @submit="handleFormSubmit"
        @cancel="handleFormCancel"
      />
      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div
          v-for="ticket in filteredTickets"
          :key="ticket.id"
          class="bg-white rounded-xl shadow-lg border border-gray-200 p-6 hover:shadow-xl transition-shadow"
        >
          <!-- Header -->
          <div class="flex items-start justify-between mb-4">
            <div class="flex-1">
              <h3 class="text-lg font-semibold text-gray-900 mb-2 line-clamp-2">
                {{ ticket.title }}
              </h3>
              <div class="flex flex-wrap gap-2">
                <span :class="[
                  'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
                  statusConfig[ticket.status]?.color || statusConfig.open.color
                ]">
                  {{ statusConfig[ticket.status]?.label || 'Open' }}
                </span>
                <span :class="[
                  'inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium',
                  priorityConfig[ticket.priority]?.color || priorityConfig.medium.color
                ]">
                  {{ priorityConfig[ticket.priority]?.label || 'Medium' }}
                </span>
              </div>
            </div>
          </div>

          <!-- Description -->
          <p v-if="ticket.description" class="text-gray-600 text-sm mb-4 line-clamp-3">
            {{ ticket.description }}
          </p>

          <!-- Dates -->
          <div class="text-xs text-gray-500 space-y-1 mb-4">
            <div>Created: {{ formatDate(ticket.createdAt) }}</div>
            <div v-if="ticket.updatedAt !== ticket.createdAt">
              Updated: {{ formatDate(ticket.updatedAt) }}
            </div>
          </div>

          <!-- Actions -->
          <div class="flex justify-between items-center pt-4 border-t border-gray-200">
            <button
              @click="handleEdit(ticket)"
              class="px-3 py-1.5 text-sm font-medium bg-gray-200 text-gray-900 rounded-lg hover:bg-gray-300 transition-colors"
            >
              Edit
            </button>
            <button
              @click="handleDelete(ticket.id)"
              class="px-3 py-1.5 text-sm font-medium bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
            >
              Delete
            </button>
          </div>
        </div>
        
        <div v-if="filteredTickets.length === 0" class="col-span-full text-center py-12">
          <div class="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg class="w-10 h-10 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          </div>
          <h3 class="text-lg font-medium text-gray-900 mb-2">No tickets found</h3>
          <p class="text-gray-600 mb-4">
            {{ filter === 'all' 
              ? "You haven't created any tickets yet."
              : `No ${filter.replace('_', ' ')} tickets found.`
            }}
          </p>
          <button
            @click="showForm = true"
            class="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors"
          >
            Create Your First Ticket
          </button>
        </div>
      </div>

      <!-- Decorative Elements -->
      <div class="w-16 h-16 bg-blue-200 rounded-full opacity-20 absolute bottom-10 right-10"></div>
      <div class="w-8 h-8 bg-green-200 rounded-full opacity-20 absolute top-20 left-10"></div>
    </div>
  </Layout>
</template>

<script>
import { ref, computed, inject } from 'vue'
import { useTickets } from '../../composables/useTickets'
import Layout from '../../components/Layout/Layout.vue'
import Button from '../../components/UI/Button.vue'
import TicketForm from './TicketForm.vue'

export default {
  name: 'TicketManagement',
  components: {
    Layout,
    Button,
    TicketForm
  },
  setup() {
    const toast = inject('toast')
    const { tickets, createTicket, updateTicket, deleteTicket } = useTickets()
    
    const showForm = ref(false)
    const editingTicket = ref(null)
    const filter = ref('all')

    const statusConfig = {
      open: { color: 'bg-green-100 text-green-800', label: 'Open' },
      in_progress: { color: 'bg-amber-100 text-amber-800', label: 'In Progress' },
      closed: { color: 'bg-gray-100 text-gray-800', label: 'Closed' }
    }

    const priorityConfig = {
      low: { color: 'bg-gray-100 text-gray-800', label: 'Low' },
      medium: { color: 'bg-blue-100 text-blue-800', label: 'Medium' },
      high: { color: 'bg-amber-100 text-amber-800', label: 'High' },
      critical: { color: 'bg-red-100 text-red-800', label: 'Critical' }
    }

    const statusCounts = computed(() => {
      return {
        all: tickets.value.length,
        open: tickets.value.filter(t => t.status === 'open').length,
        in_progress: tickets.value.filter(t => t.status === 'in_progress').length,
        closed: tickets.value.filter(t => t.status === 'closed').length
      }
    })

    const filterOptions = computed(() => [
      { status: 'all', label: 'All Tickets', count: statusCounts.value.all },
      { status: 'open', label: 'Open', count: statusCounts.value.open },
      { status: 'in_progress', label: 'In Progress', count: statusCounts.value.in_progress },
      { status: 'closed', label: 'Closed', count: statusCounts.value.closed }
    ])

    const filteredTickets = computed(() => {
      if (filter.value === 'all') return tickets.value
      return tickets.value.filter(ticket => ticket.status === filter.value)
    })

    const formatDate = (dateString) => {
      return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
    }

    const handleFormSubmit = (ticketData) => {
      if (editingTicket.value) {
        updateTicket(editingTicket.value.id, ticketData)
        toast.addToast('Ticket updated successfully!', 'success')
      } else {
        createTicket(ticketData)
        toast.addToast('Ticket created successfully!', 'success')
      }
      showForm.value = false
      editingTicket.value = null
    }

    const handleFormCancel = () => {
      showForm.value = false
      editingTicket.value = null
    }

    const handleEdit = (ticket) => {
      editingTicket.value = ticket
      showForm.value = true
    }

    const handleDelete = (ticketId) => {
      if (window.confirm('Are you sure you want to delete this ticket?')) {
        deleteTicket(ticketId)
        toast.addToast('Ticket deleted successfully!', 'success')
      }
    }

    return {
      showForm,
      editingTicket,
      filter,
      filterOptions,
      statusCounts,
      filteredTickets,
      statusConfig,
      priorityConfig,
      formatDate,
      handleFormSubmit,
      handleFormCancel,
      handleEdit,
      handleDelete
    }
  }
}
</script>
